// Icons
import WholeNote from "@/ui/svg/Notes/WholeNote";
import HalfNote from "@/ui/svg/Notes/HalfNote";
import QuarterNote from "@/ui/svg/Notes/QuarterNote";
import EighthNote from "@/ui/svg/Notes/EighthNote";
import SixteenthNote from "@/ui/svg/Notes/SixteenthNote";
import ThirtySecondNote from "@/ui/svg/Notes/ThirtySecondNote";
import SixtyFourthNote from "@/ui/svg/Notes/SixtyFourthNote";
import WholeRest from "@/ui/svg/Rests/WholeRest";
import HalfRest from "@/ui/svg/Rests/HalfRest";
import QuarterRest from "@/ui/svg/Rests/QuarterRest";
import EighthRest from "@/ui/svg/Rests/EighthRest";
import SixteenthRest from "@/ui/svg/Rests/SixteenthRest";
import ThirtySecondRest from "@/ui/svg/Rests/ThirtySecondRest";
import SixtyFourthRest from "@/ui/svg/Rests/SixtyFourthRest";

//ogarnac trzeba wymiary nutek bo niektóre są wieksze od innych, pózniej dostosowac offsety
export const NOTES = [
	{
		name: "whole note",
		icon: WholeNote,
		offsets: {
			normal: 2.3,
			flipped: 0.4,
		},
	},
	{
		name: "half note",
		icon: HalfNote,
		offsets: {
			normal: 2.3,
			flipped: 0.5,
		},
	},
	{
		name: "quarter note",
		icon: QuarterNote,
		offsets: {
			normal: 2.35,
			flipped: 0.45,
		},
	},
	{
		name: "eighth note",
		icon: EighthNote,
		offsets: {
			normal: 2.4,
			flipped: 0.35,
		},
	},
	{
		name: "sixteenth note",
		icon: SixteenthNote,
		offsets: {
			normal: 2.4,
			flipped: 0.35,
		},
	},
	{
		name: "thirty-second note",
		icon: ThirtySecondNote,
		offsets: {
			normal: 2.4,
			flipped: 0.35,
		},
	},
	{
		name: "sixty-fourth note",
		icon: SixtyFourthNote,
		offsets: {
			normal: 2.4,
			flipped: 0.35,
		},
	},
];

export const RESTS = [
	{
		name: "whole rest",
		icon: WholeRest,
		offset: 2.2,
	},
	{
		name: "half rest",
		icon: HalfRest,
		offset: 2.2,
	},
	{ name: "quarter rest", icon: QuarterRest, offset: 1.5 },
	{ name: "eighth rest", icon: EighthRest, offset: 1.2 },
	{ name: "sixteenth rest", icon: SixteenthRest, offset: 1.2 },
	{ name: "thirty-second rest", icon: ThirtySecondRest, offset: 1.2 },
	{ name: "sixty-fourth rest", icon: SixtyFourthRest, offset: 1.2 },
];

export const PITCH_MAP = [
	"G5",
	"F5",
	"E5",
	"D5",
	"C5",
	"B4",
	"A4",
	"G4",
	"F4",
	"E4",
	"D4",
];

export const NOTE_DURATIONS: { [key: string]: number } = {
	whole: 2.0, // cała nuta
	half: 1.0, // półnuta
	quarter: 0.5, // ćwierćnuta
	eighth: 0.25, // ósemka
	sixteenth: 0.125, // szesnastka
};

// Minimalna odległość po pauzie przed następną nutą
export const REST_SPACING: { [key: string]: number } = {
	whole: 180,
	half: 150,
	quarter: 120,
	eighth: 80,
	sixteenth: 60,
	"thirty-second": 40,
	"sixty-fourth": 20,
};

export const STAFF_CONSTANTS = {
	HEIGHT: 300,
	LINE_SPACING: 35,
	WIDTH: 1200,
	PADDING: 60,
	MIN_NOTE_SPACING: 60,
	PLAYBACK_LINE_SPACING: 20,
	NOTE_DRAG_OFFSET: {
		normal: 30,
		flipped: 28,
	},
};

export const furEliseNotes = [
	{
		id: "note-1733957103659",
		x: 140,
		y: 81.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "E5",
		row: 0,
	},
	{
		id: "note-1733957110292",
		x: 200,
		y: 99.25,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "D5",
		row: 0,
	},
	{
		id: "note-1733957128025",
		x: 260,
		y: 81.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "E5",
		row: 0,
	},
	{
		id: "note-1733957133609",
		x: 320,
		y: 99.25,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "D5",
		row: 0,
	},
	{
		id: "note-1733957139243",
		x: 380,
		y: 81.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "E5",
		row: 0,
	},
	{
		id: "note-1733957145261",
		x: 440,
		y: 67.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: false,
		pitch: "B4",
		row: 0,
	},
	{
		id: "note-1733957310977",
		x: 500,
		y: 99.25,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "D5",
		row: 0,
	},
	{
		id: "note-1733957316892",
		x: 560,
		y: 116.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "C5",
		row: 0,
	},
	{
		id: "note-1733957327241",
		x: 620,
		y: 85.25,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: false,
		pitch: "A4",
		row: 0,
	},
	{
		id: "note-1733957338111",
		x: 680,
		y: 125.5,
		type: "rests",
		category: "Rests",
		variant: "eighth",
		flipped: false,
		pitch: "A4",
		row: 0,
	},
	{
		id: "note-1733957342258",
		x: 820,
		y: 155.25,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: false,
		pitch: "D4",
		row: 0,
	},
	{
		id: "note-1733957346208",
		x: 880,
		y: 137.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: false,
		pitch: "E4",
		row: 0,
	},
	{
		id: "note-1733957352992",
		x: 940,
		y: 85.25,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: false,
		pitch: "A4",
		row: 0,
	},
	{
		id: "note-1733957370624",
		x: 1000,
		y: 67.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: false,
		pitch: "B4",
		row: 0,
	},
	{
		id: "note-1733957467808",
		x: 1060,
		y: 90.5,
		type: "rests",
		category: "Rests",
		variant: "eighth",
		flipped: true,
		pitch: "C5",
		row: 0,
	},
	{
		id: "note-1733957479243",
		x: 120,
		y: 136,
		type: "notes",
		category: "Notes",
		variant: "eighth",
		flipped: false,
		pitch: "E4",
		row: 1,
	},
	{
		id: "note-1733957491842",
		x: 180,
		y: 102.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: false,
		pitch: "G4",
		row: 1,
	},
	{
		id: "note-1733957499076",
		x: 240,
		y: 67.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: false,
		pitch: "B4",
		row: 1,
	},
	{
		id: "note-1733957507195",
		x: 300,
		y: 116.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "C5",
		row: 1,
	},
	{
		id: "note-1733957517991",
		x: 360,
		y: 90.5,
		type: "rests",
		category: "Rests",
		variant: "eighth",
		flipped: true,
		pitch: "C5",
		row: 1,
	},
	{
		id: "note-1733957533544",
		x: 500,
		y: 136,
		type: "notes",
		category: "Notes",
		variant: "eighth",
		flipped: false,
		pitch: "E4",
		row: 1,
	},
	{
		id: "note-1733957544242",
		x: 560,
		y: 81.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "E5",
		row: 1,
	},
	{
		id: "note-1733957549175",
		x: 620,
		y: 99.25,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "D5",
		row: 1,
	},
	{
		id: "note-1733957553942",
		x: 680,
		y: 81.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "E5",
		row: 1,
	},
	{
		id: "note-1733957559825",
		x: 740,
		y: 99.25,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "D5",
		row: 1,
	},
	{
		id: "note-1733957565307",
		x: 800,
		y: 67.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: false,
		pitch: "B4",
		row: 1,
	},
	{
		id: "note-1733957582558",
		x: 860,
		y: 99.25,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "D5",
		row: 1,
	},
	{
		id: "note-1733957590425",
		x: 920,
		y: 116.75,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: true,
		pitch: "C5",
		row: 1,
	},
	{
		id: "note-1733957601058",
		x: 980,
		y: 85.25,
		type: "notes",
		category: "Notes",
		variant: "quarter",
		flipped: false,
		pitch: "A4",
		row: 1,
	},
];
